/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estatica.view;

import Estatistica.dao.FrequentadorDAO;
import Estatistica.modelo.Frequentador;
import Estatistica.modelo.InfosTabela;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author User
 */
public class FrmFrequentadorPesquisar extends javax.swing.JFrame {

    /**
     * Creates new form FrmFrequentadorPesquisar
     */
    public FrmFrequentadorPesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtinfo = new javax.swing.JTextField();
        btnpesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("campo");

        jLabel2.setText("info");

        btnpesquisar.setText("pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        jButton1.setText("Texte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Teste2opcoes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("TesteFrequencia1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpesquisar)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtcampo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(txtinfo)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesquisar)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        Frequentador fr=new Frequentador();
        FrequentadorDAO frdao=new FrequentadorDAO();
        
        /*List frequentador=new ArrayList<Frequentador>();
        frequentador=frdao.getListFrequentadorPorInfo(txtcampo.getText(), txtinfo.getText());
        
        for(int i=0;i<frequentador.size();i++){
            System.out.println(frequentador.get(i));
        }
        */
        
        List <Frequentador> lista = frdao.getListFrequentadorPorInfo(txtcampo.getText(), txtinfo.getText());
        for (Frequentador f : lista) {
            System.out.println(f.getId() + "  "+f.getSexo()+" "+ f.getIdade() + "  "+ f.getFrequenciaSemanal() +
                    " "+ f.getEstadoCivil()+" "+ f.getMeioDeTransporte() + " "+ f.getTempoPermanencia()+" "+ f.getRendaFamiliar());
        }
        
        
        
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrequentadorDAO frdao= new FrequentadorDAO();
        List <Frequentador> listaInfo = frdao.filtrarInfo(frdao.pegarInfo(5));
        for (int i=0;i<listaInfo.size();i++) {
            System.out.println(listaInfo.get(i));
        }
        List <Frequentador> listaInfo2 = frdao.filtrarInfo(frdao.pegarInfo(6));
        for (int i=0;i<listaInfo2.size();i++) {
            System.out.println(listaInfo2.get(i));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrequentadorDAO frdao= new FrequentadorDAO();
        List <Frequentador> listaInfo = frdao.filtrarInfo(frdao.pegarInfo(5));
        for (int i=0;i<listaInfo.size();i++) {
            System.out.println(listaInfo.get(i));
        }
        List <Frequentador> listaInfo2 = frdao.filtrarInfo(frdao.pegarInfo(6));
        for (int i=0;i<listaInfo2.size();i++) {
            System.out.println(listaInfo2.get(i));
        }
        List<Frequentador> tabela=frdao.criarTabela2infos("TB_FREQUENTADOR_ESTADO_CIVIL", "TB_FREQUENTADOR_MEIO_DE_TRANSPORTE", listaInfo, listaInfo2);
        for (Frequentador f : tabela) {
            System.out.println(f.getCampo1()+ "  "+f.getCampo2());
        }
        
        
        List<Frequentador> tabela2=frdao.tabela2InfosNumeros(tabela);
        for(Frequentador f: tabela2){
            System.out.println(f.getCampo1()+"  "+f.getCampo2()+"  "+f.getCampoNumero());
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrequentadorDAO frdao= new FrequentadorDAO();        
        List<InfosTabela> tabela=frdao.tabelaFrequenciaIntervalos("TB_FREQUENTADOR_IDADE",3);
        
        DecimalFormat df = new DecimalFormat("##.00");
        
        for(InfosTabela inf: tabela){
            System.out.println(inf.getIntervalo()+ "  "+df.format(inf.getKi())+" "+ inf.getFa()+ "  "+ inf.getFr()+
                    " "+ df.format(inf.getFrPCento())+" "+ inf.getFac()+ " "+ df.format(inf.getFacPCento()));
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFrequentadorPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFrequentadorPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFrequentadorPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFrequentadorPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFrequentadorPesquisar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtcampo;
    private javax.swing.JTextField txtinfo;
    // End of variables declaration//GEN-END:variables
}
